# Generated by Django 4.0.5 on 2022-07-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_rename_name_customer_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='customers',
            field=models.ManyToManyField(related_name='services', to='crm_app.customer'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(),
        ),
    ]
